################# BASE IMAGE ######################
# Teeny-tiny matplotlib image based on alpine with Python 3.8.1
FROM --platform=linux/amd64 czentye/matplotlib-minimal:3.1.2 as base

################## METADATA ######################
LABEL base_image="matplotlib-minimal:3.1.2"
LABEL version="1.0.0"
LABEL software="MultiQC"
LABEL software.version="1.14"
LABEL about.summary="MultiQC is a reporting tool that parses summary statistics from results and log files generated by other bioinformatics tools."
LABEL about.home="https://multiqc.info/"
LABEL about.documentation="https://multiqc.info/docs/"
LABEL about.license_file="https://github.com/ewels/MultiQC/blob/master/LICENSE"
LABEL about.license="GNU GPLv3"

################## MAINTAINER ######################
MAINTAINER Matthew Galbraith <matthew.galbraith@cuanschutz.edu>
# based on https://hub.docker.com/r/ewels/multiqc/Dockerfile

################## INSTALLATION ######################

RUN apk add --no-cache bash wget tar ca-certificates

# Download and extract MultiQC
RUN wget https://github.com/ewels/MultiQC/archive/refs/tags/v1.14.tar.gz && \
	tar -xzvf v1.14.tar.gz

################## 2ND STAGE ######################
FROM --platform=linux/amd64 czentye/matplotlib-minimal:3.1.2

RUN apk add --no-cache bash

COPY --from=base /MultiQC-1.14 /MultiQC-1.14

WORKDIR /MultiQC-1.14

# Install MultiQC
RUN python -m pip install .
# pip will search /opt/mypackage for a setup.py or pyproject.toml, build a wheel, then install it.

WORKDIR /

